---
title: "Storyboard"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
---

```{r}
library(tidyverse)
library(spotifyr)
library(dplyr)
library(ggplot2)
```


```{r}

patrick <- get_playlist_audio_features("", "6wlIYjCXIv8vzRWxn8Ee9I")

```

### Frame 1

```{r}
patrick %>%
  summarise(
    mean_speechiness = mean(speechiness),
    mean_acousticness = mean(acousticness),
    mean_liveness = mean(liveness),
    sd_speechiness = sd(speechiness),
    sd_acousticness = sd(acousticness),
    sd_liveness = sd(liveness),
    median_speechiness = median(speechiness),
    median_acousticness = median(acousticness),
    median_liveness = median(liveness),
    mad_speechiness = mad(speechiness),
    mad_acousticness = mad(acousticness),
    mad_liveness = mad(liveness)
  )
```
### Frame 2

```{r}
patrick %>%
  ggplot(aes(x = speechiness)) +
  geom_histogram(binwidth = 0.01) 

```
### Frame 3

```{r}
patrick %>%
  ggplot(aes(x = speechiness, y = track.album.name)) +
  geom_point() 

```